---
id: ppb-takahiro-okumura
tags: []
version: 1.0.0
licenses: []
author:
  markup_language: :markdown
  name: Takahiro OKUMURA
  email: hfm.garden@gmail.com
  rubygems_user: hfm
  slideshare_user: hfmgarden
  speaker_deck_user: hfm
